export const SET_EXPRESSION = 'SET_EXPRESSION';

export const EVALUATE_EXPRESSION = 'EVALUATE_EXPRESSION';

export const DELETE_LAST_ENTRY = 'DELETE_LAST_ENTRY';

export const CLEAR_EXPRESSION = 'CLEAR_EXPRESSION';
